# Generated by Django 5.0.4 on 2024-04-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='driver_accepted',
        ),
        migrations.AddField(
            model_name='ride',
            name='driver_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
