# Generated by Django 5.0.4 on 2024-04-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_role_customuser_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('RIDER', 'Rider'), ('DRIVER', 'Driver')], default='RIDER', max_length=10),
        ),
    ]
