# Generated by Django 5.0.4 on 2024-04-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_role',
        ),
    ]
