# Generated by Django 5.0.4 on 2024-04-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_customuser_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('1', 'Rider'), ('2', 'Driver')], default='RIDER', max_length=10),
        ),
    ]
