# Generated by Django 5.0.4 on 2024-04-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='current_location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
