# Generated by Django 5.0.4 on 2024-04-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ride_current_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='current_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
